# Generated by Django 3.1.13 on 2022-01-24 15:28

import cporte.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PorteCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('regimen_fiscal', models.CharField(choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('609', '609 - Consolidación'), ('612', '612 - Personas Fisicas con Actividades Empresariales y Profesionales'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('632', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('628', '628 - Hidrocarburos'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes')], max_length=3)),
                ('calle', models.CharField(default='', max_length=50)),
                ('exterior', models.CharField(default='', max_length=10)),
                ('interior', models.CharField(default='', max_length=10)),
                ('colonia', models.CharField(default='', max_length=50)),
                ('cp', models.CharField(default='', max_length=5)),
                ('localidad', models.CharField(default='', max_length=20)),
                ('municipio', models.CharField(default='', max_length=20)),
                ('estado', models.CharField(default='', max_length=20)),
                ('pais', models.CharField(default='', max_length=20)),
                ('path_privateKey', models.CharField(default='', max_length=100)),
                ('path_key', models.FileField(upload_to=cporte.models.PorteCliente.upload_photo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['key'])])),
                ('path_cer', models.FileField(upload_to=cporte.models.PorteCliente.upload_photo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer'])])),
                ('path_img', models.FileField(default='', upload_to=cporte.models.PorteCliente.upload_logo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='PorteReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('calle', models.CharField(default='', max_length=50)),
                ('exterior', models.CharField(default='', max_length=10)),
                ('interior', models.CharField(default='', max_length=10)),
                ('colonia', models.CharField(default='', max_length=50)),
                ('cp', models.CharField(default='', max_length=5)),
                ('localidad', models.CharField(default='', max_length=20)),
                ('municipio', models.CharField(default='', max_length=20)),
                ('estado', models.CharField(default='', max_length=20)),
                ('pais', models.CharField(default='', max_length=20)),
                ('path_privateKey', models.CharField(default='', max_length=100)),
                ('path_key', models.FileField(upload_to=cporte.models.PorteReceiver.upload_photo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['key'])])),
                ('path_cer', models.FileField(upload_to=cporte.models.PorteReceiver.upload_photo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer'])])),
                ('porteCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cporte.portecliente')),
            ],
        ),
        migrations.CreateModel(
            name='PorteCarta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('figura', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('PorteReceiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cporte.portereceiver')),
            ],
        ),
    ]
