# Generated by Django 3.1.13 on 2022-01-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cporte', '0003_autotransporte_portefigura_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotransporte',
            name='porteCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cporte.portecliente'),
        ),
        migrations.AddField(
            model_name='portefigura',
            name='porteCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cporte.portecliente'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='porteCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cporte.portecliente'),
        ),
    ]
