# Generated by Django 3.1.13 on 2022-01-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cporte', '0004_auto_20220127_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefigura',
            name='pais',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
