# Generated by Django 3.1.13 on 2022-02-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cporte', '0005_portefigura_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='portecliente',
            name='numPermiso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portecliente',
            name='tipoPermiso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
