# Generated by Django 3.1.13 on 2022-02-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cporte', '0008_remove_portereceiver_path_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portereceiver',
            name='path_cer',
        ),
    ]
