# Generated by Django 3.1.13 on 2022-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cporte', '0009_remove_portereceiver_path_cer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portecliente',
            name='path_cer',
        ),
        migrations.RemoveField(
            model_name='portecliente',
            name='path_key',
        ),
        migrations.RemoveField(
            model_name='portecliente',
            name='path_privateKey',
        ),
    ]
