# Generated by Django 2.2.4 on 2020-01-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200129_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rason_social',
            new_name='razon_social',
        ),
    ]
