# Generated by Django 2.2.4 on 2020-01-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200130_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Latitud (coordenada)'),
        ),
        migrations.AddField(
            model_name='planta',
            name='lng',
            field=models.FloatField(blank=True, default=0, verbose_name='Longitud (coordenada)'),
        ),
    ]
