# Generated by Django 2.2.4 on 2020-02-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200213_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='status',
            field=models.CharField(blank=True, default='relevante', max_length=50),
        ),
    ]
