# Generated by Django 2.2.4 on 2020-02-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_planta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
