# Generated by Django 2.2.4 on 2020-02-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planta_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
