# Generated by Django 2.2.4 on 2020-02-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_planta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='pcapacitacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planta',
            name='pcobertura',
            field=models.IntegerField(default=0),
        ),
    ]
