# Generated by Django 2.2.4 on 2020-02-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200225_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre del contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tel_pral', models.CharField(default='', max_length=128, verbose_name='Teléfono Principal')),
                ('tel_alt', models.CharField(default='', max_length=128, verbose_name='Teléfono Alterno')),
                ('posicion', models.CharField(default='', max_length=128, verbose_name='Posición')),
                ('foto', models.ImageField(upload_to='fotos_contactos')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente')),
            ],
        ),
    ]
