# Generated by Django 2.2.4 on 2020-02-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200225_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='cinterno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contacto'),
        ),
        migrations.AddField(
            model_name='planta',
            name='giro',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='planta',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre',
            field=models.CharField(default='Nombre de planta', max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='region',
            field=models.IntegerField(blank=True, default=1, max_length=30),
        ),
    ]
