# Generated by Django 2.2.4 on 2020-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200225_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre de sucursal', max_length=128, verbose_name='Nombre')),
                ('domicilio', models.CharField(blank=True, default='', max_length=150, verbose_name='Domicilio')),
                ('telefono', models.CharField(default='', max_length=128, verbose_name='Teléfono')),
                ('ciudad', models.CharField(blank=True, default='', max_length=30, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, default='', max_length=30, verbose_name='Estado')),
                ('region', models.IntegerField(blank=True, default=1, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='planta',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='pcapacitacion',
            field=models.FloatField(default=0, verbose_name='Capacitación'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='pcobertura',
            field=models.FloatField(default=0, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='region',
            field=models.IntegerField(blank=True, default=1, max_length=30, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='status',
            field=models.CharField(blank=True, default='relevante', max_length=50, verbose_name='Estatus'),
        ),
    ]
