# Generated by Django 2.2.4 on 2020-03-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200225_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='supervidor_junior',
            new_name='supervisor_junior',
        ),
    ]
