# Generated by Django 2.2.4 on 2020-03-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200302_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='supervisor_junior',
            new_name='supervidor_junior',
        ),
    ]
