# Generated by Django 2.2.4 on 2020-03-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200302_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Planta'),
        ),
    ]
