# Generated by Django 2.2.4 on 2020-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Imagen'),
        ),
    ]
