# Generated by Django 2.2.4 on 2020-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Foto'),
        ),
    ]
