# Generated by Django 2.2.4 on 2020-03-11 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200311_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Planta'),
        ),
    ]
