# Generated by Django 2.2.4 on 2020-03-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200311_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Foto'),
        ),
    ]
