# Generated by Django 2.2.4 on 2020-03-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
