# Generated by Django 2.2.4 on 2020-03-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0026_auto_20200312_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
