# Generated by Django 2.2.4 on 2020-03-20 15:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1024, 1024], upload_to='avatars', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1024, 1024], upload_to='fotos_contactos', verbose_name='Foto'),
        ),
    ]
