# Generated by Django 2.2.4 on 2020-03-25 15:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_user_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre de planta', max_length=128, verbose_name='Nombre de la región')),
                ('alias', models.CharField(blank=True, default='', max_length=50, verbose_name='Alias de Región')),
                ('idnumerico', models.IntegerField(blank=True, verbose_name='Identfiicador numérico')),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1024, 1024], upload_to='avatars', verbose_name='Foto'),
        ),
    ]
