# Generated by Django 2.2.4 on 2020-04-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200325_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='cinterno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Contacto'),
        ),
    ]
