# Generated by Django 2.2.4 on 2020-04-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200406_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_alt',
            field=models.CharField(default='', max_length=128, verbose_name='Teléfono Alterno'),
        ),
        migrations.AddField(
            model_name='user',
            name='tel_pral',
            field=models.CharField(default='', max_length=128, verbose_name='Teléfono Principal'),
        ),
    ]
