# Generated by Django 2.2.4 on 2020-04-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200415_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='region2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Región2'),
        ),
    ]
