# Generated by Django 2.2.4 on 2020-04-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_planta_region2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='region2',
        ),
        migrations.AddField(
            model_name='planta',
            name='gradio',
            field=models.IntegerField(default=1000, verbose_name='Radio de Geocerca en Kms'),
        ),
    ]
