# Generated by Django 2.2.4 on 2020-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200423_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='polyradio',
            field=models.TextField(blank=True, null=True, verbose_name='Puntos de Geo Cerca'),
        ),
    ]
