# Generated by Django 2.2.4 on 2020-05-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200528_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
    ]
