# Generated by Django 2.2.4 on 2020-05-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_user_sitio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='user',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sitio'),
        ),
    ]
