# Generated by Django 2.2.4 on 2020-05-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200528_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sitio',
        ),
    ]
