# Generated by Django 2.2.4 on 2020-05-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_user_sitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='region',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region'),
        ),
    ]
