# Generated by Django 2.2.4 on 2020-05-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200529_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sucursal'),
        ),
    ]
