# Generated by Django 2.2.4 on 2020-05-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_sitio_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sucursal'),
        ),
    ]
