# Generated by Django 2.2.4 on 2020-06-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planta', to='core.Cliente'),
        ),
    ]
