# Generated by Django 2.2.4 on 2020-07-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200622_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='corporativo',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Corporativo'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente'),
        ),
    ]
