# Generated by Django 2.2.4 on 2020-08-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200727_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='user',
            name='no_orden',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='No. Orden'),
        ),
        migrations.AddField(
            model_name='user',
            name='transportista',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa Transportista'),
        ),
    ]
