# Generated by Django 2.2.4 on 2020-08-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20200803_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitio',
        ),
    ]
