# Generated by Django 2.2.4 on 2020-08-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_delete_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='sucursal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sucursal'),
        ),
    ]
