# Generated by Django 2.2.4 on 2020-08-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200806_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areapermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Área del Permiso')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Permiso')),
                ('desc', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('areapermiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Areapermiso')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Role')),
            ],
        ),
    ]
