# Generated by Django 2.2.4 on 2020-08-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_permrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='role',
        ),
        migrations.RemoveField(
            model_name='permrol',
            name='estado',
        ),
    ]
