# Generated by Django 2.2.4 on 2020-08-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200818_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='permrol',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
