# Generated by Django 2.2.4 on 2020-08-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_permrol_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Role'),
        ),
    ]
