# Generated by Django 2.2.4 on 2020-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_permisos_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='permrol',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
