# Generated by Django 2.2.4 on 2020-09-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
