# Generated by Django 2.2.4 on 2020-09-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Role'),
        ),
    ]
