# Generated by Django 2.2.4 on 2020-09-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_notification_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
