# Generated by Django 2.2.4 on 2020-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='idproblema',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Id_problema'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='modelo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Modelo Relacionado'),
        ),
    ]
