# Generated by Django 2.2.4 on 2020-09-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20200914_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora de Alarma'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='param_bol',
            field=models.BooleanField(default=False, verbose_name='Parámetro S/N'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='param_text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Parámetros'),
        ),
    ]
