# Generated by Django 2.2.4 on 2020-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20200915_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Token de notificacion'),
        ),
    ]
