# Generated by Django 2.2.4 on 2020-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_user_notification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=120, verbose_name='Ciudad')),
                ('codigo', models.TextField(blank=True, null=True, verbose_name='Codigo')),
            ],
        ),
    ]
