# Generated by Django 2.2.4 on 2020-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200918_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiaaR1',
            fields=[
                ('id_ciaa', models.AutoField(db_column='id_CIAA', primary_key=True, serialize=False)),
                ('cliente', models.CharField(db_column='Cliente', max_length=255)),
                ('orden', models.CharField(db_column='Orden', max_length=255)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('puesto', models.CharField(db_column='Puesto', max_length=255)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('entrada', models.CharField(db_column='Entrada', max_length=255)),
                ('salida', models.CharField(db_column='Salida', max_length=255)),
                ('hora', models.CharField(db_column='Hora', max_length=255)),
                ('geolocalizacion', models.CharField(db_column='Geolocalizacion', max_length=255)),
                ('foto', models.CharField(db_column='Foto', max_length=255)),
                ('codigo', models.CharField(db_column='Codigo', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'CIAA_R1',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
    ]
