# Generated by Django 2.2.4 on 2020-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200921_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enservicio',
            field=models.BooleanField(default=False),
        ),
    ]
