# Generated by Django 2.2.4 on 2020-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_user_enservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='gradio',
            field=models.IntegerField(default=2000, verbose_name='Radio de Geocerca en Kms'),
        ),
    ]
