# Generated by Django 2.2.4 on 2020-09-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20200928_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='estatus_estable',
            field=models.FloatField(default=0, verbose_name='Estatus Estable de Unidad de Negocio'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_relevante',
            field=models.FloatField(default=0, verbose_name='Estatus Relevante de Unidad de Negocio'),
        ),
    ]
