# Generated by Django 2.2.4 on 2020-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20200928_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='estatus_estable',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='estatus_relevante',
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_ausentismo_estable',
            field=models.FloatField(default=0, verbose_name='Estatus Estable de Ausentismo'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_ausentismo_relevante',
            field=models.FloatField(default=0, verbose_name='Estatus Relevante de Ausentismo'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_cobertura_estable',
            field=models.FloatField(default=0, verbose_name='Estatus Estable de Cobertura'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_cobertura_relevante',
            field=models.FloatField(default=0, verbose_name='Estatus Relevante de Cobertura'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_rotacion_estable',
            field=models.FloatField(default=0, verbose_name='Estatus Estable de Rotación'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estatus_rotacion_relevante',
            field=models.FloatField(default=0, verbose_name='Estatus Relevante de Rotación'),
        ),
    ]
