# Generated by Django 2.2.4 on 2020-09-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20200928_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region'),
        ),
    ]
