# Generated by Django 2.2.4 on 2020-09-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20200928_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='regiones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Región'),
        ),
    ]
