# Generated by Django 2.2.4 on 2020-09-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20200928_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='regiones',
        ),
    ]
