# Generated by Django 2.2.4 on 2020-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_remove_planta_regiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='mails_analisis_riesgo',
            field=models.TextField(blank=True, null=True, verbose_name='Emails para Notificacines en Análisis de Riesgo '),
        ),
        migrations.AddField(
            model_name='planta',
            name='mails_dd',
            field=models.TextField(blank=True, null=True, verbose_name='Emails para Notificacines en D&D Management '),
        ),
        migrations.AddField(
            model_name='planta',
            name='mails_predictive',
            field=models.TextField(blank=True, null=True, verbose_name='Emails para Notificacines en Predictive Analytics '),
        ),
        migrations.AddField(
            model_name='planta',
            name='mails_zona',
            field=models.TextField(blank=True, null=True, verbose_name='Emails para Notificacines en Zona 0 '),
        ),
    ]
