# Generated by Django 3.1.13 on 2021-09-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_computadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computadores',
        ),
    ]
