# Generated by Django 3.1.13 on 2021-12-07 18:04

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_portecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='portecliente',
            name='path_privateKey',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='portecliente',
            name='path_cer',
            field=models.FileField(upload_to=core.models.PorteCliente.upload_photo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cer'])]),
        ),
        migrations.AlterField(
            model_name='portecliente',
            name='path_key',
            field=models.FileField(upload_to=core.models.PorteCliente.upload_photo_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['key'])]),
        ),
        migrations.AlterField(
            model_name='portecliente',
            name='regimen_fiscal',
            field=models.CharField(choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('609', '609 - Consolidación'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('632', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('628', '628 - Hidrocarburos'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes')], max_length=3),
        ),
    ]
