# Generated by Django 3.1.13 on 2022-01-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cporte', '0001_initial'),
        ('core', '0089_auto_20211207_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PorteCliente',
        ),
        migrations.AddField(
            model_name='user',
            name='portecliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cporte.portecliente'),
        ),
    ]
