# Generated by Django 3.1.13 on 2022-01-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20220125_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portecliente',
        ),
    ]
