# Generated by Django 3.1.13 on 2021-09-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patio',
            name='planta',
        ),
        migrations.DeleteModel(
            name='Cajon',
        ),
        migrations.DeleteModel(
            name='Patio',
        ),
    ]
