# Generated by Django 3.1.13 on 2021-09-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_delete_computadores'),
        ('analytics', '0002_auto_20210922_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planta_patio', to='core.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_id', models.IntegerField(null=True)),
                ('disponibilidad', models.IntegerField(default=0, null=True)),
                ('tipo_caja', models.CharField(blank=True, max_length=20, null=True)),
                ('patio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.patio')),
            ],
        ),
    ]
