# Generated by Django 3.1.13 on 2021-09-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_f_previsitantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F_PreVisitantes',
        ),
    ]
