# Generated by Django 3.1.13 on 2021-09-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_f_previsitantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_es_trailers',
            name='bill_caja',
        ),
        migrations.RemoveField(
            model_name='f_es_trailers',
            name='cajon_id',
        ),
        migrations.RemoveField(
            model_name='f_es_trailers',
            name='factura_caja',
        ),
        migrations.RemoveField(
            model_name='f_es_trailers',
            name='ine_chofer',
        ),
        migrations.RemoveField(
            model_name='f_es_trailers',
            name='pedimento_caja',
        ),
    ]
