# Generated by Django 3.1.13 on 2021-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20210922_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_es_trailers',
            name='bill_caja',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/bill/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='cajon_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='factura_caja',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/factura/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='ine_chofer',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/ine/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='pedimento_caja',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/pedimento/%Y/%d/%m/'),
        ),
    ]
