# Generated by Django 3.1.13 on 2021-09-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_delete_computadores'),
        ('analytics', '0012_auto_20210922_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_es_trailers',
            name='autoriza',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='bill_caja',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/bill/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='caja',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='cajon_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='contenido_caja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='destino',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='factura_caja',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/factura/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='factura_remision_ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='firma_chofer',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/firmas/chofer/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='firma_oficial_seguridad',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/firmas/guardia/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='ine_chofer',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/ine/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='n_licencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='n_sello',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='nombre_chofer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='notas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='origen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='pedimento_caja',
            field=models.FileField(blank=True, null=True, upload_to='festrilers/documentos/pedimento/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='placas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planta'),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='f_es_trailers',
            name='transportista',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
