# Generated by Django 3.1.13 on 2021-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_f_previsitantes_fecha_agendada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_previsitantes',
            old_name='fecha_agendada',
            new_name='fecha_registro',
        ),
        migrations.AddField(
            model_name='f_previsitantes',
            name='fecha_agenda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
