# Generated by Django 3.1.13 on 2021-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_auto_20211005_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_previsitantes',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
