# Generated by Django 3.1.13 on 2021-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_auto_20211006_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_previsitantes',
            name='qr_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
