# Generated by Django 3.1.13 on 2021-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_f_previsitantes_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_visitantes',
            name='pre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='f_visitantes',
            name='qr_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='f_previsitantes',
            name='qr_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
