# Generated by Django 3.1.13 on 2021-10-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_auto_20211007_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_visitantes',
            name='fecha_agendada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
