# Generated by Django 3.1.13 on 2021-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_f_visitantes_fecha_agendada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_visitantes',
            name='gafete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
