# Generated by Django 3.1.13 on 2021-10-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_auto_20211007_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_visitantes',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='f_visitantes',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='f_visitantes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='f_visitantes',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='f_visitantes',
            name='telefono',
        ),
        migrations.DeleteModel(
            name='F_PreVisitantes',
        ),
    ]
