# Generated by Django 3.1.13 on 2021-10-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_auto_20211007_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_visitantes',
            name='pre_status',
            field=models.IntegerField(default=0),
        ),
    ]
