# Generated by Django 3.1.13 on 2021-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_f_visitantes_pre_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_visitantes',
            name='foto_ine',
            field=models.FileField(blank=True, null=True, upload_to='fotos_visitantes/ine/%Y/%d/%m/'),
        ),
    ]
