# Generated by Django 3.1.13 on 2021-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_f_visitantes_foto_ine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_visitantes',
            name='foto_ine',
        ),
        migrations.AddField(
            model_name='f_visitantes',
            name='ine_frontal',
            field=models.FileField(blank=True, null=True, upload_to='fotos_visitantes/ine_frontal/%Y/%d/%m/'),
        ),
        migrations.AddField(
            model_name='f_visitantes',
            name='ine_posterior',
            field=models.FileField(blank=True, null=True, upload_to='fotos_visitantes/ine_posterior/%Y/%d/%m/'),
        ),
    ]
