# Generated by Django 2.2.4 on 2020-01-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('path_encuesta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnes.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('orden', models.IntegerField(default=1)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnes.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=10)),
                ('repuesta', models.IntegerField()),
                ('cumple', models.IntegerField()),
                ('ocurrencia', models.IntegerField()),
                ('impacto', models.IntegerField()),
                ('resultado', models.IntegerField()),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('observacion', models.TextField()),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnes.Papeleta')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=10)),
                ('repuesta', models.IntegerField()),
                ('cumple', models.IntegerField()),
                ('ocurrencia', models.IntegerField()),
                ('impacto', models.IntegerField()),
                ('resultado', models.IntegerField()),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('observacion', models.TextField()),
                ('papeleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnes.Papeleta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnes.Pregunta')),
            ],
        ),
    ]
