# Generated by Django 2.2.4 on 2020-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0003_auto_20200225_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_encuesta',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
