# Generated by Django 2.2.4 on 2020-02-26 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0004_categoria_encuesta_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Área')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icono')),
            ],
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='coste',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='costo',
            field=models.BooleanField(default=False, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='vulnerabilidad',
            field=models.IntegerField(default=10, verbose_name='Vulnerabilidad'),
        ),
        migrations.AlterField(
            model_name='categoria_encuesta',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='categoria_encuesta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de Categoría Encuesta'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='path_encuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='evidenciarecomendacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='evidenciarecomendacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='evidenciarecomendacion',
            name='nota',
            field=models.TextField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Compromiso'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='ponderacion',
            field=models.FloatField(verbose_name='Ponderación'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='status',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('vencido', 'Vencido'), ('cumplido', 'Cumplido'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=100, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='user_aguilas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacion_user_aguilas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='user_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Segmento')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arnes.Area')),
            ],
        ),
    ]
