# Generated by Django 2.2.4 on 2020-02-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0005_auto_20200226_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='req_evidencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.TextField(),
        ),
    ]
