# Generated by Django 2.2.4 on 2020-02-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0006_auto_20200226_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='pregunta_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arnes.Pregunta'),
        ),
    ]
