# Generated by Django 2.2.4 on 2020-02-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200225_1456'),
        ('arnes', '0007_auto_20200226_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='planta',
        ),
        migrations.AddField(
            model_name='papeleta',
            name='planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='papeleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arnes.Papeleta'),
            preserve_default=False,
        ),
    ]
