# Generated by Django 2.2.4 on 2020-02-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0008_auto_20200227_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='repuesta',
            new_name='respuesta',
        ),
        migrations.RemoveField(
            model_name='papeleta',
            name='ciudad',
        ),
    ]
