# Generated by Django 2.2.4 on 2020-06-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0009_auto_20200227_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='valor',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='papeleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='arnes.Papeleta'),
        ),
    ]
