# Generated by Django 2.2.4 on 2020-07-23 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0048_auto_20200722_1028'),
        ('arnes', '0011_auto_20200722_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Jornada')),
                ('esquema', models.SmallIntegerField(default=0, verbose_name='Esquema')),
            ],
        ),
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de recibido')),
                ('nota', models.TextField(default='', verbose_name='Nota')),
                ('destinatario', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Planta')),
                ('user_aguilas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recibio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
