# Generated by Django 2.2.4 on 2020-07-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0012_jornada_paqueteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentracion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='concentracion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='concentracion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='concentracion',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='concentracion',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='concentracion',
            name='sitio',
        ),
        migrations.RemoveField(
            model_name='concentracion',
            name='user_aguilas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='grado',
        ),
        migrations.DeleteModel(
            name='Jornada',
        ),
        migrations.RemoveField(
            model_name='paqueteria',
            name='un',
        ),
        migrations.RemoveField(
            model_name='paqueteria',
            name='user_aguilas',
        ),
        migrations.DeleteModel(
            name='Categoria_Curso',
        ),
        migrations.DeleteModel(
            name='Concentracion',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Paqueteria',
        ),
    ]
