# Generated by Django 2.2.4 on 2020-09-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0013_auto_20200723_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencia/recoemdaciones/%Y/%m/%d/', verbose_name='Evidencia'),
        ),
    ]
