# Generated by Django 2.2.4 on 2020-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0014_recomendacion_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='status',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('vencido', 'Vencido'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=100, verbose_name='Estatus'),
        ),
    ]
