# Generated by Django 3.1.13 on 2022-02-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0020_auto_20220204_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria_encuesta',
            name='analisis',
        ),
    ]
