# Generated by Django 3.1.13 on 2022-02-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0021_remove_categoria_encuesta_analisis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_encuesta',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de Categoria Encuesta'),
        ),
    ]
