# Generated by Django 3.1.13 on 2022-02-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arnes', '0024_remove_categoria_encuesta_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_encuesta',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arnes.analisis'),
        ),
    ]
