# Generated by Django 2.2.4 on 2020-01-29 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asalto_transeuntes', 'Asalto a transeuntes'), ('asalto_negocio', 'Asalto a negocio'), ('casa_habitacion', 'Casa habitacion'), ('homicidio', 'Homicidio'), ('secuestro', 'Secuestro'), ('carjacking', 'Carjacking'), ('habitacion', 'Habitacion'), ('hotel', 'Hotel')], max_length=30, verbose_name='Tipo')),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(blank=True, default='', max_length=150)),
                ('pais', models.CharField(blank=True, default='', max_length=30)),
                ('ciudad', models.CharField(blank=True, default='', max_length=30)),
                ('estado', models.CharField(blank=True, default='', max_length=30)),
                ('cantidad', models.IntegerField(default=1)),
                ('lat', models.FloatField(blank=True, default=0, verbose_name='Latitud (coordenada)')),
                ('lng', models.FloatField(blank=True, default=0, verbose_name='Longitud (coordenada)')),
                ('url_noticia', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
