# Generated by Django 2.2.4 on 2020-02-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entorno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
