# Generated by Django 2.2.4 on 2020-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entorno', '0003_auto_20200211_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidente',
            name='hora',
            field=models.TimeField(default='07:00'),
        ),
    ]
