# Generated by Django 2.2.4 on 2020-02-25 23:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200225_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entorno', '0005_incidente_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('alias', models.CharField(max_length=30, verbose_name='Alias')),
                ('icono', models.ImageField(upload_to='tipo_incidentes_iconos')),
            ],
        ),
        migrations.RemoveField(
            model_name='alarma',
            name='fecha',
        ),
        migrations.AddField(
            model_name='alarma',
            name='accion',
            field=models.TextField(default='', verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='estatus',
            field=models.CharField(choices=[('relevante', 'RELEVANTE'), ('normal', 'NORMAL'), ('pendiente', 'PENDIENTE')], default='normal', max_length=30, verbose_name='Estatus de Alarma'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='hora_fin',
            field=models.TimeField(default='7:00'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='hora_inicio',
            field=models.TimeField(default='7:00'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='incidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entorno.Incidente'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='tipo',
            field=models.CharField(default='', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entorno.TipoIncidente'),
        ),
    ]
