# Generated by Django 2.2.4 on 2020-02-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('unidad_valor', models.CharField(blank=True, default='', max_length=30)),
                ('tiempo_estimado', models.FloatField()),
                ('nombre_chofer', models.CharField(blank=True, default='', max_length=50)),
                ('matricula', models.CharField(blank=True, default='', max_length=30)),
                ('destino', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
