# Generated by Django 2.2.4 on 2020-08-01 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0049_auto_20200727_0943'),
        ('ddmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.CharField(max_length=100, verbose_name='Empresa transportista')),
                ('infocarga', models.TextField(blank=True, max_length=800, null=True, verbose_name='Información de la Carga')),
                ('tipo_movimiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de movimiento')),
                ('doc_completa', models.BooleanField(default=False, verbose_name='¿Documentación completa?')),
                ('origen', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion de origen')),
                ('destino', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion destino')),
                ('origen_coords', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordenadas de origen')),
                ('destino_coords', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordenadas de destino')),
                ('tiempo_estimado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo estimado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo de Salida')),
                ('estatus', models.CharField(blank=True, default='Normal', max_length=30, null=True, verbose_name='Estatus')),
                ('confirmacion', models.BooleanField(default=False, verbose_name='Confirmación por Monitorista de Traslado Finalizado?')),
                ('remolque', models.CharField(blank=True, max_length=30, null=True, verbose_name='Identificador del remolque')),
                ('valor_carga', models.CharField(default='', max_length=50, verbose_name='Valor en carga')),
                ('peso', models.CharField(default='', max_length=50, verbose_name='Peso de carga')),
                ('gls', models.FloatField(verbose_name='Gls.')),
                ('lts', models.FloatField(verbose_name='Gls.')),
                ('puente', models.BooleanField(default=False)),
                ('peaje', models.FloatField(verbose_name='Gls.')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_chofer', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Planta')),
                ('relevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_relevo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('decripcion', models.CharField(max_length=150, verbose_name='Descripcion corta')),
            ],
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='company',
            new_name='compania',
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=50, verbose_name='Placas')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.CharField(max_length=10, verbose_name='Año')),
                ('seria', models.CharField(max_length=50, verbose_name='No. de Serie')),
                ('tipo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.TipoVehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=65, size=[1024, 1024], upload_to='fotos_tickets', verbose_name='Foto')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.Movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.Vehiculo'),
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('folio', models.CharField(max_length=50, verbose_name='Folio')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddmanagement.Movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, verbose_name='Identificador')),
                ('capacidad', models.CharField(max_length=50, verbose_name='Capacidad')),
                ('tipo', models.CharField(max_length=50, verbose_name='Identificador')),
                ('sello', models.CharField(default='', max_length=30, verbose_name='Sello')),
                ('movimiento', models.ManyToManyField(related_name='get_cajas', to='ddmanagement.Movimiento', verbose_name='Movimiento')),
            ],
        ),
    ]
