# Generated by Django 2.2.4 on 2020-08-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0002_auto_20200801_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='sello',
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sello', models.CharField(default='', max_length=30, verbose_name='Sello')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajamov', to='ddmanagement.Caja', verbose_name='Caja')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_movimiento', to='ddmanagement.Movimiento', verbose_name='Movimiento')),
            ],
        ),
    ]
