# Generated by Django 2.2.4 on 2020-08-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0003_auto_20200803_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovehiculo',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chofer_movimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='relevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevo_movimiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
