# Generated by Django 2.2.4 on 2020-08-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0004_auto_20200803_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de caja'),
        ),
    ]
