# Generated by Django 2.2.4 on 2020-08-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0005_auto_20200803_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='tipo',
            field=models.CharField(choices=[('Materia prima', 'Materia prima'), ('Producto terminado', 'Producto terminado'), ('Producto de ensamble', 'Producto de ensamble'), ('Folio / Shipper', 'Folio / Shipper'), ('Peso (en toneladas)', 'Peso (en toneladas)')], max_length=50, verbose_name='Tipo'),
        ),
    ]
