# Generated by Django 2.2.4 on 2020-08-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0006_auto_20200803_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiempo de Salida'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='gpsid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='gpstracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsid', models.CharField(blank=True, max_length=20, null=True)),
                ('momento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.Vehiculo')),
            ],
        ),
    ]
