# Generated by Django 2.2.4 on 2020-08-04 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0007_auto_20200804_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='lts',
            field=models.FloatField(verbose_name='Lts.'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='peaje',
            field=models.FloatField(verbose_name='Peaje.'),
        ),
        migrations.CreateModel(
            name='IncidenteVial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigpslat', models.FloatField(verbose_name='Ubicación Lat')),
                ('ubigpslng', models.FloatField(verbose_name='Ubicación Lng')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo del Incidente Vial')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Incidente')),
                ('notas', models.TextField(max_length=700, verbose_name='Observaciones')),
                ('estatus', models.CharField(max_length=20, verbose_name='Estatus')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.Movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaIncidenteVial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.FileField(upload_to='evidencias/viales/%Y/%d/%m/')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.IncidenteVial')),
            ],
        ),
    ]
