# Generated by Django 2.2.4 on 2020-08-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0008_auto_20200804_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empelado_foraneo', models.CharField(max_length=50, verbose_name='Nombre del Empleado Foraneo')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Logro')),
                ('nombre_logro', models.CharField(max_length=50, verbose_name='Nombre del Logro')),
                ('motivo', models.CharField(max_length=254, verbose_name='Motivo')),
                ('accion_realizada', models.CharField(max_length=254, verbose_name='Motivo')),
                ('status', models.CharField(max_length=50, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nombre de la Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(default='', max_length=128, verbose_name='Teléfono')),
                ('domicilio', models.CharField(default='', max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('imagen_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
