# Generated by Django 2.2.4 on 2020-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0009_logro_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='imagen_logo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_proveedores', verbose_name='Imagen'),
        ),
    ]
