# Generated by Django 2.2.4 on 2020-08-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0010_auto_20200806_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='transportista',
        ),
    ]
