# Generated by Django 2.2.4 on 2020-08-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0012_movimiento_prov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logro',
            name='empelado_foraneo',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='prov',
        ),
        migrations.AddField(
            model_name='logro',
            name='empleado_foraneo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Empleado'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='status',
            field=models.CharField(choices=[('Completado', 'Completado'), ('Por Terminar', 'Por Terminar'), ('Iniciado', 'Iniciado')], max_length=50, verbose_name='Estatus'),
        ),
    ]
