# Generated by Django 2.2.4 on 2020-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0015_movimiento_emp_transp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=50, verbose_name='Empresa Transportista'),
        ),
    ]
