# Generated by Django 2.2.4 on 2020-08-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0016_auto_20200812_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaincidentevial',
            name='incidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencia_incidente_vial', to='ddmanagement.IncidenteVial'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_tickets', to='ddmanagement.Movimiento'),
        ),
    ]
