# Generated by Django 2.2.4 on 2020-08-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0017_auto_20200812_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpsdevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(blank=True, max_length=10, null=True)),
                ('devicename', models.CharField(blank=True, max_length=20, null=True)),
                ('asignado', models.BooleanField(default=False, verbose_name='Asignado')),
            ],
        ),
    ]
