# Generated by Django 2.2.4 on 2020-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0018_gpsdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='deviceesn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
