# Generated by Django 2.2.4 on 2020-08-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0019_gpsdevice_deviceesn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='gpsdevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.gpsdevice'),
        ),
    ]
