# Generated by Django 2.2.4 on 2020-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0022_auto_20200818_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='ef',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿Llegó a tiempo?'),
        ),
    ]
