# Generated by Django 2.2.4 on 2020-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0023_movimiento_ef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='ef',
            field=models.BooleanField(default=False),
        ),
    ]
