# Generated by Django 2.2.4 on 2020-08-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0024_auto_20200821_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Tiempo de Salida'),
        ),
    ]
