# Generated by Django 2.2.4 on 2020-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0025_auto_20200828_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Medio', 'Medio'), ('Relevante', 'Relevante')], default='Normal', max_length=30, null=True, verbose_name='Estatus'),
        ),
    ]
