# Generated by Django 2.2.4 on 2020-09-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_permrol_estado'),
        ('ddmanagement', '0026_auto_20200901_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente'),
        ),
    ]
