# Generated by Django 2.2.4 on 2020-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0027_gpsdevice_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(blank=True, choices=[(2, 'Camino Bloqueado'), (2, 'Climatológico'), (2, 'Demora en carga'), (2, 'Demora en descarga'), (2, 'Detención por Federales'), (2, 'Detención por Guardia Nacional'), (2, 'Detención por Tránsito'), (2, 'Descanso'), (2, 'Falla Mecánica Leve-Moderada'), (2, 'Incendio'), (2, 'Incidencia en DOT'), (2, 'Manifestación / Huelga'), (2, 'Ponchadura de neumáticos'), (2, 'Problema de Salud'), (2, 'Otro')], max_length=50, null=True, verbose_name='Tipo de movimiento'),
        ),
    ]
