# Generated by Django 2.2.4 on 2020-09-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0029_auto_20200903_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(blank=True, default=1, max_length=50, null=True, verbose_name='Tipo de movimiento'),
        ),
    ]
