# Generated by Django 2.2.4 on 2020-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0031_movimiento_tipo_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_incidente',
            field=models.IntegerField(blank=True, choices=[(1, 'Normal'), (2, 'Camino Bloqueado'), (2, 'Climatológico'), (2, 'Demora en carga'), (2, 'Demora en descarga'), (2, 'Detención por Federales'), (2, 'Detención por Guardia Nacional'), (2, 'Detención por Tránsito'), (2, 'Descanso'), (2, 'Falla Mecánica Leve-Moderada'), (2, 'Incendio'), (2, 'Incidencia en DOT'), (2, 'Manifestación / Huelga'), (2, 'Ponchadura de neumáticos'), (2, 'Problema de Salud'), (3, 'Falla mecánica grave'), (3, 'Carga equivocada'), (3, 'Incidente Vial'), (3, 'Contaminación de carga'), (3, 'Decomiso de Mercancía'), (3, 'Robo'), (2, 'Otro')], default=1, max_length=50, null=True, verbose_name='Tipo de Incidente'),
        ),
    ]
