# Generated by Django 2.2.4 on 2020-09-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0034_auto_20200903_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logro',
        ),
    ]
