# Generated by Django 2.2.4 on 2020-09-08 23:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0035_delete_logro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='waypoints',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
