# Generated by Django 2.2.4 on 2020-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0036_movimiento_waypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de movimiento'),
        ),
    ]
