# Generated by Django 2.2.4 on 2020-09-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0037_auto_20200910_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='¿Disponible?'),
        ),
    ]
