# Generated by Django 2.2.4 on 2020-09-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0038_vehiculo_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Disponible?'),
        ),
    ]
