# Generated by Django 2.2.4 on 2020-09-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0039_auto_20200910_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre / Alias del Movimiento'),
        ),
    ]
