# Generated by Django 2.2.4 on 2020-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0040_movimiento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='sobreruta',
            field=models.BooleanField(default=True),
        ),
    ]
