# Generated by Django 2.2.4 on 2020-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0041_movimiento_sobreruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estatus',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Medio', 'Medio'), ('Relevante', 'Relevante'), ('Finalizado', 'Finalizado')], default='Normal', max_length=30, null=True, verbose_name='Estatus'),
        ),
    ]
