# Generated by Django 2.2.4 on 2020-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0042_auto_20201002_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='caja_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. de Caja'),
        ),
        migrations.AddField(
            model_name='caja',
            name='caja_placas',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Placas de la caja'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cajaeco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Económico de la caja'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sellocaja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sello de Caja'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='economico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Económico'),
        ),
    ]
