# Generated by Django 2.2.4 on 2020-10-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0043_auto_20201014_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='infocarga',
            field=models.TextField(default='', verbose_name='Información de la Carga'),
        ),
    ]
