# Generated by Django 3.1.13 on 2022-01-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0045_movimiento_n_sello'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='tipo',
            field=models.BooleanField(default=False, verbose_name='tipo_dispositivo'),
        ),
    ]
