from .views import *
from .perfiles.views_perfiles_global import *
from .perfiles.views_perfiles_clientes import *
from .perfiles.views_perfiles_clientes_new import *
from .perfiles.views_perfiles_personal import *
from .unidades_negocio.views_unidades_negocio import *
from .unidades_negocio.views_unidad_negocio import *
from .rondines.views_rondines import *
from .sucursales.views_sucursales import *
from .mapa_delictivo.views_mapa_delictivo import *
from .mapa_delictivo.viewa_ajax_mapa_delictivo import *
#Zona 0
from .zona0.views_incidentes import *
#Predictive Analytics
from .predictive_analytics.views_ajax_dashboard import *
from .predictive_analytics.views_es_trailers import *
from .predictive_analytics.views_18puntos import *
from .predictive_analytics.views_paqueteria import *
from .predictive_analytics.views_empleadosg import *
from .predictive_analytics.views_area import *
from .predictive_analytics.views_categorias_cursos import *
from .predictive_analytics.views_cursos import * 
from .predictive_analytics.views_grados import *
from .predictive_analytics.views_concentracion import *
from .predictive_analytics.views_visitantes import *
from .predictive_analytics.views_visitantes_new import *
from .predictive_analytics.views_recibo_almacen import *
from .predictive_analytics.views_logro import *
# Analisis de Riesgo
from .analisis_de_riesgo.views_papeletas import *
from .analisis_de_riesgo.views_resultados_analisis_riesgo import *
#D&D Management
from .ddmanagement.views_movimientos import *
from .ddmanagement.views_tipo_movimientos import *
from .ddmanagement.views_proveedores import *
from .ddmanagement.views_tipo_vehiculo import *
from .ddmanagement.views_caja import *
from .ddmanagement.views_cargas import *
from .ddmanagement.views_chofer import * 
from .ddmanagement.views_vehiculo import *
from .ddmanagement.views_gpsdevices import *
from .ddmanagement.views_proveedor import *
from .ddmanagement.views_ajax_movimientos import *
from .ddmanagement.views_dashboard import * 
from .ddmanagement.views_ajax_gpsdevices import  *  
#Cuentas
from .cuentas.views_cuentas import *
from .areas_permisos.views_areas_permisos import *
from .permisos.views_permisos import *