"""Django settings for panoptic project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import sys, os, io
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@duiyzedg4ddz89tn%a#kb@-ri##+mvq!hs8xj@k#jbv3wng1y'

GOOGLE_RECAPTCHA_SITE_KEY = "6Le03FgdAAAAABjl8q-VcKssKFv2IlCD7w6m1h0C"

GOOGLE_RECAPTCHA_SECRET_KEY = "6Le03FgdAAAAACC9eKnIYHEtOwgqf6xIi87lgigA"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['*']

INTERNAL_IPS = [    
    '127.0.0.1',    
] 


# Application definition

INSTALLED_APPS = [
    'registration',
    'clearcache',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'entorno',       
    'arnes',
    'analytics',
    'ddmanagement',
    'cporte',
    'administrador',
    'django_tables2',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'rest_framework',
    'API',
    'qrcode',
    'django.contrib.sites',
    'debug_toolbar',
    'rest_framework.authtoken',
    #'channels',
    #'channels_redis'
    'shapely',
    'django_cleanup.apps.CleanupConfig', #al final de la lista siempre
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

SITE_ID  = 2

AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'panoptic.urls'

DATA_UPLOAD_MAX_MEMORY_SIZE = 76214400

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'administrador.processors.permisoZona0',
                'administrador.processors.permisoAnalisisRiesgo',
                'administrador.processors.permisoDD',
                'administrador.processors.permisoCPorte',
                'administrador.processors.permisoPredictive',
                'administrador.processors.permisoBackstage',
            ],
        },
    },
]

WSGI_APPLICATION = 'panoptic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Servidor https://198.12.148.250 User panoptic
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '127.0.0.1',
            #'NAME': 'Panoptic',
            'NAME': 'mxpanoptic',
            'USER': 'root',
            'PASSWORD': '$DesTec2022',
            #'PASSWORD': '$AES-128-CBC$T4TKthXvzXDnBj+pl8EfGA==$VGxI1zo8yZW/NlS2rtxsnw==',
            'OPTIONS': {
            'autocommit': True,
            },
        },
        'aguilas': {
            'ENGINE': 'django.db.backends.mysql',
            #'HOST': '45.76.57.170',
            'HOST': '165.227.27.68',
            'NAME': 'u1iens_prueba1',
            #'USER': 'u1iens_amartin',
            #'PASSWORD': 'Aguilas@1234',
            'USER': 'u1iens',
            'PASSWORD': '![fduX!DY[sM',
            'OPTIONS': {
            'autocommit': True,
            },  
        }
    }     


DATABASE_ROUTERS = ['core.routers.AguilasRouter'] 

"""
if DEBUG == False: # En producción

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '198.12.148.250',
            'NAME': 'panoptic_iotrem',
            'USER': 'panoptic_uzrremp',
            'PASSWORD': 'TeospJI%Ezdc',
            'OPTIONS': {
            'autocommit': True,
            },
        }
    }      
else: # En local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': 'localhost',
            'NAME': 'panoptic',
            'USER': 'root',
            'PASSWORD': '',
            'OPTIONS': {
            'autocommit': True,
            },
        }
    }
"""

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Chihuahua'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#LOGIN_REDIRECT_URL = reverse_lazy('inicio')
LOGIN_REDIRECT_URL = reverse_lazy('ceo_global')

LOGOUT_REDIRECT_URL = reverse_lazy('login')

ASGI_APPLICATION = 'panoptic.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379),],
        }
    }
}
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder'
]

PLOTLY_COMPONENTS = [

    'dash_core_components',
    'dash_html_components',
    'dash_renderer',
    'dpd_components'
]

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
)



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'

#Emails
#if DEBUG:
 #   EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
  #  EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails") 
#else:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'jesus.camarillo@iottechnologies.mx'
EMAIL_HOST_PASSWORD = 'pxrtqoidnegseevy'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'admin@grupoaguilas.com'

# Media files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
