# Generated by Django 2.2.4 on 2020-08-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0010_auto_20200806_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddmanagement.Proveedor'),
        ),
    ]
