# Generated by Django 2.2.4 on 2020-08-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0011_auto_20200807_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='transportista',
        ),
    ]
