# Generated by Django 2.2.4 on 2020-08-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddmanagement', '0013_movimiento_transportista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='transportista',
        ),
    ]
